# Certain lines of code are commented out so that the API is not rerun

In [3]:
import requests
import pandas as pd

url = "https://realty-mole-property-api.p.rapidapi.com/zipCodes/29611"

headers = {
    'x-rapidapi-host': "realty-mole-property-api.p.rapidapi.com",
    'x-rapidapi-key': "9bf1c65e0fmsh39efdd5cc4f3d3fp15f361jsn585706dcd8ee"
    }

#response = requests.request("GET", url, headers=headers).json()

print(response)

{'id': '29611', 'rentalData': {'averageRent': 992.64, 'minRent': 595, 'maxRent': 2500, 'totalRentals': 66, 'detailed': [{'bedrooms': 0, 'averageRent': 878.6, 'minRent': 635, 'maxRent': 1305, 'totalRentals': 5}, {'bedrooms': 1, 'averageRent': 722.5, 'minRent': 595, 'maxRent': 1265, 'totalRentals': 6}, {'bedrooms': 2, 'averageRent': 951.36, 'minRent': 695, 'maxRent': 1495, 'totalRentals': 22}, {'bedrooms': 3, 'averageRent': 1249.75, 'minRent': 770, 'maxRent': 2500, 'totalRentals': 28}, {'bedrooms': 4, 'averageRent': 1161, 'minRent': 995, 'maxRent': 1320, 'totalRentals': 5}], 'history': {'2020-04': {'averageRent': 965.26, 'minRent': 595, 'maxRent': 2500, 'totalRentals': 70, 'detailed': [{'bedrooms': 0, 'averageRent': 878.6, 'minRent': 635, 'maxRent': 1305, 'totalRentals': 5}, {'bedrooms': 1, 'averageRent': 728.75, 'minRent': 595, 'maxRent': 1345, 'totalRentals': 8}, {'bedrooms': 2, 'averageRent': 905.63, 'minRent': 695, 'maxRent': 1200, 'totalRentals': 30}, {'bedrooms': 3, 'averageRent': 1186.32, 'minRent': 750, 'maxRent': 2500, 'totalRentals': 22}, {'bedrooms': 4, 'averageRent': 1127, 'minRent': 975, 'maxRent': 1295, 'totalRentals': 5}]}, '2020-05': {'averageRent': 967.55, 'minRent': 595, 'maxRent': 2500, 'totalRentals': 71, 'detailed': [{'bedrooms': 0, 'averageRent': 878.6, 'minRent': 635, 'maxRent': 1305, 'totalRentals': 5}, {'bedrooms': 1, 'averageRent': 716.25, 'minRent': 595, 'maxRent': 1345, 'totalRentals': 8}, {'bedrooms': 2, 'averageRent': 915.14, 'minRent': 695, 'maxRent': 1175, 'totalRentals': 29}, {'bedrooms': 3, 'averageRent': 1212.76, 'minRent': 750, 'maxRent': 2500, 'totalRentals': 25}, {'bedrooms': 4, 'averageRent': 1115, 'minRent': 975, 'maxRent': 1295, 'totalRentals': 4}]}, '2020-06': {'averageRent': 990.83, 'minRent': 595, 'maxRent': 2500, 'totalRentals': 70, 'detailed': [{'bedrooms': 0, 'averageRent': 878.6, 'minRent': 635, 'maxRent': 1305, 'totalRentals': 5}, {'bedrooms': 1, 'averageRent': 712.14, 'minRent': 595, 'maxRent': 1265, 'totalRentals': 7}, {'bedrooms': 2, 'averageRent': 940.32, 'minRent': 695, 'maxRent': 1495, 'totalRentals': 28}, {'bedrooms': 3, 'averageRent': 1221.85, 'minRent': 770, 'maxRent': 2500, 'totalRentals': 26}, {'bedrooms': 4, 'averageRent': 1201.25, 'minRent': 995, 'maxRent': 1320, 'totalRentals': 4}]}, '2020-07': {'averageRent': 992.64, 'minRent': 595, 'maxRent': 2500, 'totalRentals': 66, 'detailed': [{'bedrooms': 0, 'averageRent': 878.6, 'minRent': 635, 'maxRent': 1305, 'totalRentals': 5}, {'bedrooms': 1, 'averageRent': 722.5, 'minRent': 595, 'maxRent': 1265, 'totalRentals': 6}, {'bedrooms': 2, 'averageRent': 951.36, 'minRent': 695, 'maxRent': 1495, 'totalRentals': 22}, {'bedrooms': 3, 'averageRent': 1249.75, 'minRent': 770, 'maxRent': 2500, 'totalRentals': 28}, {'bedrooms': 4, 'averageRent': 1161, 'minRent': 995, 'maxRent': 1320, 'totalRentals': 5}]}}}}

In [5]:
import pandas as pd
test=pd.DataFrame(response)
test

                 id                                         rentalData
averageRent   29611                                             992.64
detailed      29611  [{'bedrooms': 0, 'averageRent': 878.6, 'minRen...
history       29611  {'2020-04': {'averageRent': 965.26, 'minRent':...
maxRent       29611                                               2500
minRent       29611                                                595
totalRentals  29611                                                 66

In [7]:
url = "https://realty-mole-property-api.p.rapidapi.com/zipCodes/80003"

headers = {
    'x-rapidapi-host': "realty-mole-property-api.p.rapidapi.com",
    'x-rapidapi-key': "9bf1c65e0fmsh39efdd5cc4f3d3fp15f361jsn585706dcd8ee"
    }

#response = requests.request("GET", url, headers=headers)

print(response.text)

{"id":"80003","rentalData":{"averageRent":1846.94,"minRent":750,"maxRent":2995,"totalRentals":66,"detailed":[{"bedrooms":0,"averageRent":1388.14,"minRent":1098,"maxRent":1995,"totalRentals":7},{"bedrooms":1,"averageRent":1097.14,"minRent":750,"maxRent":1350,"totalRentals":7},{"bedrooms":2,"averageRent":1617.43,"minRent":1300,"maxRent":1850,"totalRentals":14},{"bedrooms":3,"averageRent":2073.42,"minRent":1695,"maxRent":2600,"totalRentals":19},{"bedrooms":4,"averageRent":2273.81,"minRent":1895,"maxRent":2783,"totalRentals":16},{"bedrooms":5,"averageRent":2631.67,"minRent":2400,"maxRent":2995,"totalRentals":3}],"history":{"2020-04":{"averageRent":1807.66,"minRent":750,"maxRent":2897,"totalRentals":66,"detailed":[{"bedrooms":0,"averageRent":1405.88,"minRent":1017,"maxRent":1995,"totalRentals":8},{"bedrooms":1,"averageRent":1077.86,"minRent":750,"maxRent":1495,"totalRentals":14},{"bedrooms":2,"averageRent":1426.92,"minRent":950,"maxRent":1800,"totalRentals":12},{"bedrooms":3,"averageRent":2093.44,"minRent":950,"maxRent":2725,"totalRentals":16},{"bedrooms":4,"averageRent":2241.87,"minRent":800,"maxRent":2897,"totalRentals":15},{"bedrooms":5,"averageRent":2600,"minRent":2600,"maxRent":2600,"totalRentals":1}]},"2020-05":{"averageRent":1813.1,"minRent":750,"maxRent":2648,"totalRentals":62,"detailed":[{"bedrooms":0,"averageRent":1399.13,"minRent":1017,"maxRent":1995,"totalRentals":8},{"bedrooms":1,"averageRent":1087.22,"minRent":750,"maxRent":1495,"totalRentals":9},{"bedrooms":2,"averageRent":1528.17,"minRent":1250,"maxRent":1800,"totalRentals":12},{"bedrooms":3,"averageRent":2198,"minRent":1725,"maxRent":2600,"totalRentals":15},{"bedrooms":4,"averageRent":2166.06,"minRent":800,"maxRent":2648,"totalRentals":17},{"bedrooms":5,"averageRent":2500,"minRent":2500,"maxRent":2500,"totalRentals":1}]},"2020-06":{"averageRent":1802.27,"minRent":750,"maxRent":2648,"totalRentals":67,"detailed":[{"bedrooms":0,"averageRent":1415,"minRent":1065,"maxRent":1995,"totalRentals":8},{"bedrooms":1,"averageRent":1056.25,"minRent":750,"maxRent":1350,"totalRentals":8},{"bedrooms":2,"averageRent":1595.23,"minRent":1250,"maxRent":1850,"totalRentals":13},{"bedrooms":3,"averageRent":2145.28,"minRent":1695,"maxRent":2600,"totalRentals":18},{"bedrooms":4,"averageRent":2151.83,"minRent":800,"maxRent":2648,"totalRentals":18},{"bedrooms":5,"averageRent":2450,"minRent":2400,"maxRent":2500,"totalRentals":2}]},"2020-07":{"averageRent":1846.94,"minRent":750,"maxRent":2995,"totalRentals":66,"detailed":[{"bedrooms":0,"averageRent":1388.14,"minRent":1098,"maxRent":1995,"totalRentals":7},{"bedrooms":1,"averageRent":1097.14,"minRent":750,"maxRent":1350,"totalRentals":7},{"bedrooms":2,"averageRent":1617.43,"minRent":1300,"maxRent":1850,"totalRentals":14},{"bedrooms":3,"averageRent":2073.42,"minRent":1695,"maxRent":2600,"totalRentals":19},{"bedrooms":4,"averageRent":2273.81,"minRent":1895,"maxRent":2783,"totalRentals":16},{"bedrooms":5,"averageRent":2631.67,"minRent":2400,"maxRent":2995,"totalRentals":3}]}}}}

In [18]:
response.json()

{'id': '80003',
 'rentalData': {'averageRent': 1846.94,
  'minRent': 750,
  'maxRent': 2995,
  'totalRentals': 66,
  'detailed': [{'bedrooms': 0,
    'averageRent': 1388.14,
    'minRent': 1098,
    'maxRent': 1995,
    'totalRentals': 7},
   {'bedrooms': 1,
    'averageRent': 1097.14,
    'minRent': 750,
    'maxRent': 1350,
    'totalRentals': 7},
   {'bedrooms': 2,
    'averageRent': 1617.43,
    'minRent': 1300,
    'maxRent': 1850,
    'totalRentals': 14},
   {'bedrooms': 3,
    'averageRent': 2073.42,
    'minRent': 1695,
    'maxRent': 2600,
    'totalRentals': 19},
   {'bedrooms': 4,
    'averageRent': 2273.81,
    'minRent': 1895,
    'maxRent': 2783,
    'totalRentals': 16},
   {'bedrooms': 5,
    'averageRent': 2631.67,
    'minRent': 2400,
    'maxRent': 2995,
    'totalRentals': 3}],
  'history': {'2020-04': {'averageRent': 1807.66,
    'minRent': 750,
    'maxRent': 2897,
    'totalRentals': 66,
    'detailed': [{'bedrooms': 0,
      'averageRent': 1405.88,
      'minRent': 1017,
      'maxRent': 1995,
      'totalRentals': 8},
     {'bedrooms': 1,
      'averageRent': 1077.86,
      'minRent': 750,
      'maxRent': 1495,
      'totalRentals': 14},
     {'bedrooms': 2,
      'averageRent': 1426.92,
      'minRent': 950,
      'maxRent': 1800,
      'totalRentals': 12},
     {'bedrooms': 3,
      'averageRent': 2093.44,
      'minRent': 950,
      'maxRent': 2725,
      'totalRentals': 16},
     {'bedrooms': 4,
      'averageRent': 2241.87,
      'minRent': 800,
      'maxRent': 2897,
      'totalRentals': 15},
     {'bedrooms': 5,
      'averageRent': 2600,
      'minRent': 2600,
      'maxRent': 2600,
      'totalRentals': 1}]},
   '2020-05': {'averageRent': 1813.1,
    'minRent': 750,
    'maxRent': 2648,
    'totalRentals': 62,
    'detailed': [{'bedrooms': 0,
      'averageRent': 1399.13,
      'minRent': 1017,
      'maxRent': 1995,
      'totalRentals': 8},
     {'bedrooms': 1,
      'averageRent': 1087.22,
      'minRent': 750,
      'maxRent': 1495,
      'totalRentals': 9},
     {'bedrooms': 2,
      'averageRent': 1528.17,
      'minRent': 1250,
      'maxRent': 1800,
      'totalRentals': 12},
     {'bedrooms': 3,
      'averageRent': 2198,
      'minRent': 1725,
      'maxRent': 2600,
      'totalRentals': 15},
     {'bedrooms': 4,
      'averageRent': 2166.06,
      'minRent': 800,
      'maxRent': 2648,
      'totalRentals': 17},
     {'bedrooms': 5,
      'averageRent': 2500,
      'minRent': 2500,
      'maxRent': 2500,
      'totalRentals': 1}]},
   '2020-06': {'averageRent': 1802.27,
    'minRent': 750,
    'maxRent': 2648,
    'totalRentals': 67,
    'detailed': [{'bedrooms': 0,
      'averageRent': 1415,
      'minRent': 1065,
      'maxRent': 1995,
      'totalRentals': 8},
     {'bedrooms': 1,
      'averageRent': 1056.25,
      'minRent': 750,
      'maxRent': 1350,
      'totalRentals': 8},
     {'bedrooms': 2,
      'averageRent': 1595.23,
      'minRent': 1250,
      'maxRent': 1850,
      'totalRentals': 13},
     {'bedrooms': 3,
      'averageRent': 2145.28,
      'minRent': 1695,
      'maxRent': 2600,
      'totalRentals': 18},
     {'bedrooms': 4,
      'averageRent': 2151.83,
      'minRent': 800,
      'maxRent': 2648,
      'totalRentals': 18},
     {'bedrooms': 5,
      'averageRent': 2450,
      'minRent': 2400,
      'maxRent': 2500,
      'totalRentals': 2}]},
   '2020-07': {'averageRent': 1846.94,
    'minRent': 750,
    'maxRent': 2995,
    'totalRentals': 66,
    'detailed': [{'bedrooms': 0,
      'averageRent': 1388.14,
      'minRent': 1098,
      'maxRent': 1995,
      'totalRentals': 7},
     {'bedrooms': 1,
      'averageRent': 1097.14,
      'minRent': 750,
      'maxRent': 1350,
      'totalRentals': 7},
     {'bedrooms': 2,
      'averageRent': 1617.43,
      'minRent': 1300,
      'maxRent': 1850,
      'totalRentals': 14},
     {'bedrooms': 3,
      'averageRent': 2073.42,
      'minRent': 1695,
      'maxRent': 2600,
      'totalRentals': 19},
     {'bedrooms': 4,
      'averageRent': 2273.81,
      'minRent': 1895,
      'maxRent': 2783,
      'totalRentals': 16},
     {'bedrooms': 5,
      'averageRent': 2631.67,
      'minRent': 2400,
      'maxRent': 2995,
      'totalRentals': 3}]}}}}

In [22]:
zips=[75001, 80123, 64131, 99205]

zip_codes=[]
average_rent=[]
min_rent=[]
max_rent=[]
total_rentals=[]

# for each_zip in zips:
#     url = f"https://realty-mole-property-api.p.rapidapi.com/zipCodes/{each_zip}"
#     headers = {
#         'x-rapidapi-host': "realty-mole-property-api.p.rapidapi.com",
#         'x-rapidapi-key': "9bf1c65e0fmsh39efdd5cc4f3d3fp15f361jsn585706dcd8ee"
#         }
#     response = requests.request("GET", url, headers=headers).json()
#     zip_codes.append(response["id"])
#     average_rent.append(response["rentalData"]["averageRent"])
#     min_rent.append(response["rentalData"]["minRent"])
#     max_rent.append(response["rentalData"]["maxRent"])
#     total_rentals.append(response["rentalData"]["totalRentals"])



test_df=pd.DataFrame({
    "Zip Code": zip_codes,
    "Average Rent": average_rent,
    "Minimum Rent": min_rent,
    "Maximum Rent": max_rent,
    "Total Rentals": total_rentals
})

test_df["City"]=["Addison", "Littleton", "Kansas City", "Spokane"]
test_df["State"]=["TX", "CO", "MO", "WA"]
test_df

,Zip Code,Average Rent,Minimum Rent,Maximum Rent,Total Rentals,City,State
0,75001,1949.47,769,3200,65,Addison,TX
1,80123,2110.63,495,5500,70,Littleton,CO
2,64131,1020.59,475,2500,69,Kansas City,MO
3,99205,1167.33,450,3500,111,Spokane,WA